# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-
$:.push File.expand_path("../lib", __FILE__)
require 'kaltura_fu/version'

Gem::Specification.new do |s|
  s.name = %q{kaltura_fu}
  s.version = KalturaFu::VERSION.dup

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Patrick Robertson"]
  s.date = %q{2011-04-20}
  s.email = %q{patrick.robertson@velir.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = Dir['[A-Z]*','lib/**/*','rails/**/*','spec/**/*']
  s.homepage = %q{http://github.com/Velir/kaltura_fu}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Rails gem for making Kaltura integrations easier.}
  s.test_files = Dir['spec/**/*']
  s.add_dependency('velir_kaltura-ruby', '~> 0.4')
  
  s.add_development_dependency('rspec', '~> 2.6.0')
  s.add_development_dependency('activesupport', '~> 3.0')
end

